version: "3.9"

services:
  server:
    image: 'clickhouse/clickhouse-server:latest'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
